generate:
	python3 generator.py

run_h1:
	python3 run_h1.py > log1.txt

run_h2:
	python3 run_h2.py > log2.txt

run_h3:
	python3 run_h3.py > log3.txt

run_h4:
	python3 run_h4.py > log4.txt

test_puzzle:
	python3 test_puzzle.py

test_solution:
	python3 test_solution.py